# Generated by Django 2.2.5 on 2022-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220327_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('irr', 'IRR'), ('krw', 'KRW'), ('trl', 'TRL')], default='usd', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('EN', 'English'), ('KR', 'Korean'), ('TR', 'Turkish'), ('FR', 'Persian')], default='EN', max_length=3, null=True),
        ),
    ]
