# Generated by Django 2.2.5 on 2022-04-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220408_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmation',
            new_name='email_verified',
        ),
    ]
